---
title: "Untitled"
author: "TMM"
date: '2022-05-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(terra)
library(ggbiplot)
library(tidyverse)
```

```{r read_env_files}
# environmental data
env <- terra::rast('../data/environmental_data/envdata_1km_no_corr_noNA.grd')
```

```{r load_species_files}
## What about new locations - do they make sense?
method = c("none", "uncertainty", "prevalence", "unc_plus_prev", "unc_plus_recs", "coverage")

method_locs <- data.frame()

for(com in 1:1) { # community
  
  for(a in 1:4){ # adaptive sampling version
    print(a)
    
    for(m in seq_along(method)) {
      
      cov <- readRDS(paste0('../outputs/comm4_asv1_investigating/asv',a,'_v4community_', com, '_50_sim_initial_AS_', method[m], '.rds'))
      
      obvs <- data.frame()
      
      for(i in 1:length(cov)) {
        obvs <- rbind(obvs, cbind(cov[[i]]$observations[,1:2], species = paste0('Sp',i))) 
      }
      
      obvs$id <- paste(obvs$lon, obvs$lat)
      obvs$method <- method[m]
      obvs$asv <- ifelse(a == 1, 0.1, 
                         ifelse(a == 2, 0.01,
                                ifelse(a == 3, 0, 
                                       ifelse(a == 4, 0.5))))
      obvs$community <- com
      
      method_locs <- rbind(method_locs,obvs)
      
    }
  }
  
}

head(method_locs)
```

```{r reduce_data_size}

# get initial observations for each species
obvsinit <- readRDS('../outputs/comm4_asv1_investigating/v4community_1_50_sim_initial.rds')

init_obvs <- data.frame()
for(i in 1:length(obvsinit)) {
  os <- obvsinit[[i]]$observations[!is.na(obvsinit[[i]]$observations$Observed),]
  init_obvs <- rbind(init_obvs, cbind(os[,1:2], species = paste0('Sp',i))) 
}

obvsinit2 <- init_obvs %>% 
  dplyr::select(!species) %>% 
  distinct() %>% 
  mutate(method = 'initial',
         id = paste(lon, lat))
head(obvsinit2)


# find the new locs that weren't the initial locs
no_spp <- method_locs[!method_locs$id %in% obvsinit2$id,] %>% 
  dplyr::select(lon, lat, method, asv, community) %>% 
  distinct()

init_nspp <- obvsinit2 %>% 
  dplyr::select(lon, lat, method) %>% 
  mutate(asv='init',
         community = 1)

no_spp <- rbind(no_spp, init_nspp)
glimpse(no_spp)
```


```{r true_distribution}

true_obvs <- data.frame()
for(i in 1:length(obvsinit)) {
  true_obvs <- rbind(true_obvs, cbind(obvsinit[[i]]$observations[,1:2], species = paste0('Sp',i))) 
}

true_obvs2 <- true_obvs  %>% 
  dplyr::select(lon, lat) %>% 
  distinct() %>% 
  mutate(method = 'true',
         asv='true',
         community = 1)
head(true_obvs2)

no_spp <- rbind(no_spp, true_obvs2)
```


```{r extract_env}
env_loc <- terra::extract(env, no_spp[,1:2])
edat <- cbind(no_spp, env_loc)

head(edat)
```


```{r PCA}
pc <- prcomp(edat %>% 
               dplyr::select(7:39),
             scale. = T,
             center = T)
# glimpse(pc)
# plot(pc)
# summary(pc)

ggplot(data.frame(pc$x), aes(PC1, PC2)) +
  geom_point() +
  # stat_bin2d() +
  facet_wrap(edat$method~edat$asv)
```

```{r plot_func, include = FALSE}
ggbpl <- function (pcobj, choices = 1:2, scale = 1, pc.biplot = TRUE, 
                   obs.scale = 1 - scale, var.scale = scale, groups = NULL, 
                   ellipse = FALSE, ellipse.prob = 0.68, labels = NULL, labels.size = 3, 
                   alpha = 1, var.axes = TRUE, circle = FALSE, circle.prob = 0.69, 
                   varname.size = 3, varname.adjust = 1.5, varname.abbrev = FALSE, 
                   ...) 
{
  library(ggplot2)
  library(plyr)
  library(scales)
  library(grid)
  stopifnot(length(choices) == 2)
  if (inherits(pcobj, "prcomp")) {
    nobs.factor <- sqrt(nrow(pcobj$x) - 1)
    d <- pcobj$sdev
    u <- sweep(pcobj$x, 2, 1/(d * nobs.factor), FUN = "*")
    v <- pcobj$rotation
  }
  choices <- pmin(choices, ncol(u))
  df.u <- as.data.frame(sweep(u[, choices], 2, d[choices]^obs.scale, 
                              FUN = "*"))
  v <- sweep(v, 2, d^var.scale, FUN = "*")
  df.v <- as.data.frame(v[, choices])
  names(df.u) <- c("xvar", "yvar")
  names(df.v) <- names(df.u)
  if (pc.biplot) {
    df.u <- df.u * nobs.factor
  }
  r <- sqrt(qchisq(circle.prob, df = 2)) * prod(colMeans(df.u^2))^(1/4)
  v.scale <- rowSums(v^2)
  df.v <- r * df.v/sqrt(max(v.scale))
  if (obs.scale == 0) {
    u.axis.labs <- paste("standardized PC", choices, sep = "")
  }
  else {
    u.axis.labs <- paste("PC", choices, sep = "")
  }
  u.axis.labs <- paste(u.axis.labs, sprintf("(%0.1f%% explained var.)", 
                                            100 * pcobj$sdev[choices]^2/sum(pcobj$sdev^2)))
  if (!is.null(labels)) {
    df.u$labels <- labels
  }
  if (!is.null(groups)) {
    df.u$groups <- groups
  }
  if (varname.abbrev) {
    df.v$varname <- abbreviate(rownames(v))
  }
  else {
    df.v$varname <- rownames(v)
  }
  df.v$angle <- with(df.v, (180/pi) * atan(yvar/xvar))
  df.v$hjust = with(df.v, (1 - varname.adjust * sign(xvar))/2)
  g <- ggplot(data = df.u, aes(x = xvar, y = yvar)) + xlab(u.axis.labs[1]) + 
    ylab(u.axis.labs[2]) + coord_equal()
  if (var.axes) {
    
    g <- g + geom_segment(data = df.v, aes(x = 0, y = 0, 
                                           xend = xvar, yend = yvar), 
                          arrow = arrow(length = unit(1/2, "picas")), color = muted("red"))
  }
  if (!is.null(df.u$groups) && ellipse) {
    theta <- c(seq(-pi, pi, length = 50), seq(pi, -pi, length = 50))
    circle <- cbind(cos(theta), sin(theta))
    ell <- ddply(df.u, "groups", function(x) {
      if (nrow(x) <= 2) {
        return(NULL)
      }
      sigma <- var(cbind(x$xvar, x$yvar))
      mu <- c(mean(x$xvar), mean(x$yvar))
      ed <- sqrt(qchisq(ellipse.prob, df = 2))
      data.frame(sweep(circle %*% chol(sigma) * ed, 2, 
                       mu, FUN = "+"), groups = x$groups[1])
    })
    names(ell)[1:2] <- c("xvar", "yvar")
    g <- g + geom_path(data = ell, aes(color = groups, group = groups))
  }
  if (var.axes) {
    # g <- g + geom_text(data = df.v, aes(label = varname, 
    #   x = xvar, y = yvar, angle = angle, hjust = hjust), 
    #   color = "darkred", size = varname.size)
  }
  return(list(plot = g,
              ellip_dat = ell,
              arrow_dat = df.v))
}

```


```{r}
gdf <- ggbpl(pc,
             obs.scale = 1,
             var.scale = 1,
             groups = interaction(edat$method, edat$asv),
             ellipse = TRUE,
             circle = FALSE,
             ellipse.prob = 0.68,
             var.axes = T)
g <- gdf$plot + scale_color_discrete(name = '')
g <- g + theme(legend.direction = 'horizontal',
               legend.position = 'top') +
  theme_classic()
print(g)
```

```{r}

elp <- gdf$ellip_dat %>% 
  separate(groups, into = c('method', 'asv'), sep = "\\.", extra = 'merge')
head(elp)

init <- data.frame(do.call(rbind, replicate(length(unique(elp$method[elp$method != 'initial'])),
                                            as.matrix(elp[elp$method=='initial',]), simplify=FALSE)))

init$method <- rep(unique(elp$method[elp$method!='initial']), 
                   each = nrow((elp[elp$method=='initial',])))


true <- data.frame(do.call(rbind, replicate(length(unique(elp$method[elp$method != 'true'])),
                                            as.matrix(elp[elp$method=='true',]), simplify=FALSE)))

true$method <- rep(unique(elp$method[elp$method!='true']), 
                   each = nrow((elp[elp$method=='true',])))

elpdf <- rbind(elp, init, true) %>% 
  mutate(x = as.numeric(xvar),
         y = as.numeric(yvar))

ggplot(elpdf[elpdf$method!='initial' & elpdf$method!='true',], aes(x,y,col = factor(asv))) +
  geom_path(size = 0.7) +
  xlab('PC1') + ylab('PC2') +
  facet_wrap(~method) +
  theme_bw()


ggplot(elpdf[elpdf$method!='initial' & elpdf$asv!='init',], aes(x,y,col = method)) +
  geom_path(size = 0.7) +
  xlab('PC1') + ylab('PC2') +
  facet_wrap(~factor(asv)) +
  theme_bw()

```


```{r}

dfmeth <- ggbpl(pc,
                obs.scale = 1,
                var.scale = 1,
                groups = edat$method,
                ellipse = TRUE,
                circle = FALSE,
                ellipse.prob = 0.68,
                var.axes = T)

dfasv <- ggbpl(pc,
               obs.scale = 1,
               var.scale = 1,
               groups = edat$asv,
               ellipse = TRUE,
               circle = FALSE,
               ellipse.prob = 0.68,
               var.axes = T)


ggplot(dfasv$ellip_dat, aes(xvar, yvar, col = groups, group = groups)) +
  xlab('PC1') + ylab('PC2') +
  geom_path()

ggplot(dfmeth$ellip_dat, aes(xvar, yvar, col = groups, group = groups)) +
  xlab('PC1') + ylab('PC2') +
  geom_path()

```


### hypervolumes

```{r}

library(hypervolume)

df_as1_unc <- subset(edat, method == 'uncertainty' & asv == 0.01) %>% 
  dplyr::select(7:39) %>% 
  mutate_if(is.numeric, scale)
df_init <- subset(edat, method == 'initial') %>% 
  dplyr::select(7:39) %>% 
  mutate_if(is.numeric, scale)

# Generate Hypervolumes
hv_as1unc = hypervolume(df_as1_unc,name='as1_unc',samples.per.point=10) # warning about dimensionality - too many dimensions for number of obervations
hv_init = hypervolume(df_init,name='init',samples.per.point=10)

# Method 1: 2hr runtime with 12 threads
combined_sample = rbind(df_as1_unc, df_init)
population_hat = hypervolume(combined_sample)

# Create bootstrapped hypervolumes of both sample sizes
method1_path_size_1669 = hypervolume_resample("quercus_1669_boot", population_hat, "bootstrap", n = 100, cores = 8)
method1_path_size_2110 = hypervolume_resample("quercus_2110_boot", population_hat, "bootstrap", n = 100, cores = 8)


result1 = hypervolume_overlap_test(hv_alba, hv_rubra, c(method1_path_size_1669, method1_path_size_2110), cores = 8)



```


